import {Container, Grid, Paper, TextField, InputBase, Button} from '@material-ui/core';
import Head from 'next/head';
import React from 'react';
import useStyles from '../styles/Contact';
// import Image1 from '../public/Illustrator.png';
import Image from 'next/image';

const Contact = () => {
  const classes = useStyles ();

  return (
    <div>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container className={classes.root}>
          <Grid container spacing={1} alignItems="center" justifyContent="space-around">
            <Grid item lg={4}>
            {/* This Image is not available check again */}
              {/* <Image src={Image1} /> */}
            </Grid>
            <Grid item lg={5}>
              <Paper className={classes.paper}>
                <Grid container spacing={4} direction="column">
                  <Grid item >
                      <InputBase className={classes.input} placeholder="Your Name" />
                  </Grid>
                  <Grid item >
                      <InputBase className={classes.input} placeholder="Your Email" />
                  </Grid>
                  <Grid item >
                      <InputBase rows="4" className={classes.input} placeholder="Drop a message..." />
                  </Grid>
                </Grid>
                <Grid item>
                  <Button className={classes.button}>Submit</Button>
                </Grid>
              </Paper>
            </Grid>
          </Grid>
        </Container>
        <h1>Contact</h1>
      </main>
    </div>
  );
};

export default Contact;
